functional:
  - Пользователь может искать товары по ключевому слову.
  - Пользователь может фильтровать товары.
  - Пользователь может просматривать товары и подробную информацию о товаре.
  - Пользователь может добавлять товары в корзину.
  - Пользователь может удалять товар из корзины.
  - Пользователь может изменять количество товара в корзине.
  - Пользователь может оформить заказ с переходом на страницу оплаты.
  - Пользователь может переключить язык интерфейса.
  - Корзина хранится в сессии браузера.

non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть доступен на мобильных устройствах.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен поддерживать локализацию на русский и английский языки.
  - Сайт должен быть оптимизирован для скорости работы.

implicit:
  - Сайт должен быть доступен 24/7.
  - Данные пользователя (корзина) должны сохраняться даже при обновлении страницы.
  - Пользователь должен визуально видеть изменения при добавлении товара в корзину (например, уведомление или обновление значка корзины).
  - Сайт должен корректно обрабатывать пустую корзину (например, отображать сообщение "Ваша корзина пуста").
  - Фильтры и поиск должны работать быстро и корректно.
  - Товары должны быть доступны для просмотра только авторизованным пользователям (если требуется регистрация).
  - Сайт должен корректно обрабатывать ошибки при оплате: если транзакция не завершается, пользователь должен получить уведомление об ошибке и возможность повторить попытку.
  - Сайт должен быть защищен от спама и ботов (например, с помощью CAPTCHA или аналогичных механизмов).
  - Пользователь должен иметь возможность вернуться к каталогу товаров после оформления заказа.
  - Интерфейс должен быть интуитивно понятным: элементы управления (кнопки, меню, фильтры) должны быть расположены логично и удобно для восприятия.